export { default as Login } from "./Login";
export { default as Login2 } from "./Login2";
export { default as Main } from "./Main";
export { default as Main2 } from "./Main2";
export { default as Error } from "./Error";
export { default as Boat } from "./Boat";
export { default as Land } from "./Land";
export { default as Info } from "./Info";
export { default as Board } from "./Board";
